### ISSUE TITLE
Cannot be installed using devmenu

### ISSUE THREAD

**Issue by kot2002** [The-4n/4NXCI#5] opened 2018-08-05 09:48 UTC
Converted NSPs cannot be installed using devmenu.

And installed apps does not run on open-source CFWs. (sig-patched atmosphere, ReiNX, etc.)

But if you install update NSPs for them, it runs normally.

It seems that games which have no updates only run on SX OS currently.

**Comment by chronoss09** [comment] 2018-08-06 11:09
Something for me too, the game can't launch...

**Comment by The-4n** [comment] 2018-08-06 18:47
the issue is resolved in v0.9-alpha.3

**Closed** 2018-08-06 18:47 UTC
